---
- name: pause module demo
  hosts: all
  vars:
    wait_seconds: 5
  tasks:

    # This is module for ansible pause module
    - name: pause for {{ wait_seconds | int }} second(s)
      ansible.builtin.pause:
        seconds: "{{ wait_seconds | int }}"
      
    # Debug message
    - name: message
      ansible.builtin.debug:
        msg: "the end"

    # Pause until the any user input
    - name: pause until the user input
      ansible.builtin.pause:
        prompt: "Enter something or press any key to continue"
    
    # Print message after pause
    - name: print message after pause
      ansible.builtin.debug:
        msg: Playbook execution after pause