---
- name: tag example playbook
  hosts: localhost
  gather_facts: false
  tasks:
    
    - name: hello from tag1
      ansible.builtin.debug:
        msg: "hello from tag1"
      tags: tag1

    - name: Start service
      ansible.builtin.debug:
        msg: "This is tag2 and tag3"
      tags:
        - tag2
        - tag3

    - name: example for tag names
      ansible.builtin.debug:
        msg: "Hello from http and config"
      tags:
        - firewall
        - configure
