
- name: Lineinfile playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Upgrade all packages
    package:
      name: "*"
      state: latest
  - name: Install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - apache2
    - telnet
    - unzip
